"""
Flyway / Liquibase versioning helper
─────────────────────────────────────
Wraps the generated schema.sql into a versioned migration file that
Flyway or Liquibase can track and apply idempotently.

Flyway naming convention:
  V<version>__<description>.sql
  e.g.  V20240527_001__migrate_mssql_dbo.sql

Usage (standalone):
  python -m utils.flyway_versioner \
    --input ./audited \
    --out   ./flyway/migrations \
    --version 20240527_001 \
    --description migrate_mssql_adventureworks
"""

import argparse
import os
import re
import json
from datetime import datetime

from utils.logger import get_logger

logger = get_logger("flyway")


def sanitise_description(desc: str) -> str:
    """Convert a description string to Flyway-safe format (alphanumeric + underscore)."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", desc).strip("_")


def generate_flyway_migration(
    audited_dir: str,
    output_dir: str,
    version: str | None = None,
    description: str = "migrate_mssql",
    include_header: bool = True,
) -> str:
    """
    Read schema.sql from audited_dir and write a versioned Flyway migration file.

    Returns the path to the generated file.
    """
    schema_path = os.path.join(audited_dir, "schema.sql")
    if not os.path.exists(schema_path):
        raise FileNotFoundError(f"schema.sql not found in {audited_dir}")

    with open(schema_path, encoding="utf-8") as f:
        schema_sql = f.read()

    # Auto-generate version from timestamp if not provided
    if not version:
        version = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    safe_desc = sanitise_description(description)
    filename  = f"V{version}__{safe_desc}.sql"

    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, filename)

    # Build file content
    parts = []

    if include_header:
        # Load compatibility report summary if present
        report_path = os.path.join(audited_dir, "compatibility_report.json")
        report_summary = ""
        if os.path.exists(report_path):
            with open(report_path, encoding="utf-8") as f:
                report = json.load(f)
            s = report.get("summary", {})
            report_summary = (
                f"-- Audit: gate={s.get('gate','?')}  "
                f"blockers={s.get('blockers',0)}  "
                f"warnings={s.get('warnings',0)}  "
                f"info={s.get('info',0)}"
            )

        parts.append(f"""-- ============================================================
-- Flyway migration: {filename}
-- Generated by etl_migrator at {datetime.utcnow().isoformat()}Z
-- Source: MSSQL  ->  Target: PostgreSQL
{report_summary}
-- ============================================================
""")

    parts.append(schema_sql)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))

    logger.info("Flyway migration written: %s", out_path)
    return out_path


# ── Standalone CLI ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="flyway_versioner",
        description="Wrap audited schema.sql into a versioned Flyway migration file",
    )
    parser.add_argument("--input",       required=True, help="Audited directory (contains schema.sql)")
    parser.add_argument("--out",         required=True, help="Output directory for migration file")
    parser.add_argument("--version",     default=None,  help="Version string (default: timestamp)")
    parser.add_argument("--description", default="migrate_mssql", help="Migration description")
    args = parser.parse_args()

    path = generate_flyway_migration(
        audited_dir=args.input,
        output_dir=args.out,
        version=args.version,
        description=args.description,
    )
    print(f"Generated: {path}")


if __name__ == "__main__":
    main()
